import { frontmatter, markdownList, slugify } from "../core/format.js";
import { DEFAULT_SESSION_DATE, summarizeEvents } from "../pipeline/events.js";

export function buildBrainFiles(session, events, options = {}) {
  const sessionDate = options.sessionDate ?? DEFAULT_SESSION_DATE;
  const slug = slugify(session.sessionId || session.title);
  return [
    ["RESOLVER.md", buildResolver()],
    ["schema.md", buildSchema()],
    ["README.md", buildDirReadme("TerryGam Office Brain", "Physical context memory generated by the TerryGam office companion.")],
    ["meetings/README.md", buildDirReadme("Meetings", "Speaker-separated physical-room conversations, decisions, risks, and follow-ups.")],
    ["sources/README.md", buildDirReadme("Sources", "Raw or lightly-normalized inputs that generated brain pages.")],
    ["sources/physical-room/README.md", buildDirReadme("Physical Room Sources", "Raw TerryGam room observations, transcripts, robot attention events, and memory-write ledgers.")],
    [`meetings/${slug}.md`, buildMeetingPage(session, events, { sessionDate })],
    [`sources/physical-room/${slug}.events.jsonl`, `${events.map((event) => JSON.stringify(event)).join("\n")}\n`],
  ];
}

export function buildMeetingPage(session, events, options = {}) {
  const sessionDate = options.sessionDate ?? DEFAULT_SESSION_DATE;
  const slug = slugify(session.sessionId || session.title);
  const { transcript, context, memoryWrites, gaze, reactions } = summarizeEvents(events);
  const decisions = memoryWrites.filter((event) => event.payload?.type === "decision");
  const risks = memoryWrites.filter((event) => event.payload?.type === "risk");
  const whiteboard = [
    ...context.filter((event) => event.kind?.toLowerCase() === "whiteboard"),
    ...memoryWrites.filter((event) => event.payload?.type === "whiteboard_observation"),
  ];

  const summary = [
    "This session demonstrates TerryGam's physical-context loop: room audio, robot attention, visual whiteboard observations, and structured memory writes.",
    "The team aligned around a founder-friendly pricing test while surfacing enterprise trust as the main unresolved risk.",
    "The whiteboard captured the same decision/risk shape plus a demo-Friday proof point.",
  ];

  return `${frontmatter({
    title: `${session.title} - physical context session`,
    type: "meeting",
    source: "terrygam-office",
    session_id: session.sessionId,
    date: sessionDate,
    tags: ["terrygam", "physical-context", "office-memory", "replay"],
  })}

# ${session.title} - ${sessionDate}

> Executive summary: ${summary[0]}

## State

- **Capture mode:** Replay seed for the TerryGam office companion.
- **Physical layers:** Vision, audio, and embodied robot reactions.
- **Memory target:** GBrain source \`terrygam-office\`.
- **Raw event ledger:** [${slug}.events.jsonl](../sources/physical-room/${slug}.events.jsonl)

## Summary

${summary.map((item) => `- ${item}`).join("\n")}

## Speaker-Separated Transcript

${markdownList(transcript, (event) => `- **${event.speaker}:** ${event.text}`)}

## Context Cards

${markdownList(context, (event) => `- **${event.kind}:** ${event.text}`)}

## Decisions

${markdownList(decisions, (event) => `- ${event.payload.text}`)}

## Risks

${markdownList(risks, (event) => `- ${event.payload.text}`)}

## Whiteboard And Room Observations

${markdownList(whiteboard, (event) => {
  const text = event.payload?.text ?? event.text;
  return `- ${text}`;
})}

## Robot Attention And Reactions

${markdownList(gaze, (event) => `- At ${event.at_ms}ms, Reachy gaze target: \`${event.target}\`.`)}
${markdownList(reactions, (event) => `- At ${event.at_ms}ms, Reachy reaction: ${event.text}.`)}

## Memory Writes

${markdownList(memoryWrites, (event) => `- **${event.payload.type}:** ${event.payload.text}`)}

---

## Timeline

- **${sessionDate}** | TerryGam replay session - Captured a small-team pricing debate with speaker-separated transcript, context cards, robot attention, and memory-write events. [Source: TerryGam replay, ${sessionDate}]
`;
}

function buildResolver() {
  return `# TerryGam Office Brain Resolver

This brain source stores physical-room context captured by TerryGam.

## Filing Rules

1. Meeting-like conversations go in \`meetings/\`.
2. Raw room/event ledgers go in \`sources/physical-room/\`.
3. Whiteboard observations stay attached to the relevant meeting until they become durable ideas, projects, or concepts.
4. Generated pages should preserve speaker labels and source timing when available.

`;
}

function buildSchema() {
  return `# TerryGam Office Brain Schema

Each physical-context page should preserve:

- What happened in the room.
- Who spoke, at least as stable speaker labels.
- What Reachy saw or attended to.
- What decisions, risks, questions, and follow-ups were extracted.
- Raw source pointers for replay, audit, and later reprocessing.

`;
}

function buildDirReadme(name, purpose) {
  return `# ${name}

${purpose}

`;
}

